# Use the official image as a parent image
FROM postgres:latest

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Make port 5432 available to the world outside this container
EXPOSE 5432